---
all:
  children:
    smo:
      hosts:
        hpe15:
          ansible_host: localhost
          ansible_connection: local
          deployment_type: smo
    
    near_rt_ric:
      hosts:
        hpe16:
          ansible_host: localhost
          ansible_connection: local
          deployment_type: near_rt_ric

